<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_8UcopsUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.8UcopsU' shared service.
     *
     * @return \App\Service\ServicioEjemplo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LeerCsvController::readCsv()": the $ejemplo argument is type-hinted with the non-existent class or interface: "App\\Service\\ServicioEjemplo".');
    }
}
