<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvReaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sTrlr3Q.App\Service\CsvReader' shared service.
     *
     * @return \App\Service\CsvReader
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sTrlr3Q": it references class "App\\Service\\CsvReader" but no such service exists.');
    }
}
