<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeerCsvControllerreadCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sTrlr3Q.App\Controller\LeerCsvController::readCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sTrlr3Q.App\\Controller\\LeerCsvController::readCsv()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csvReader' => ['privates', '.errored..service_locator.sTrlr3Q.App\\Service\\CsvReader', NULL, 'Cannot autowire service ".service_locator.sTrlr3Q": it references class "App\\Service\\CsvReader" but no such service exists.'],
            'ejemplo' => ['privates', '.errored.8UcopsU', NULL, 'Cannot determine controller argument for "App\\Controller\\LeerCsvController::readCsv()": the $ejemplo argument is type-hinted with the non-existent class or interface: "App\\Service\\ServicioEjemplo".'],
        ], [
            'csvReader' => 'App\\Service\\CsvReader',
            'ejemplo' => '?',
        ]))->withContext('App\\Controller\\LeerCsvController::readCsv()', $container);
    }
}
