<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicioEjemploService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ServicioEjemplo' shared autowired service.
     *
     * @return \App\Services\ServicioEjemplo
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ServicioEjemplo.php';

        return $container->privates['App\\Services\\ServicioEjemplo'] = new \App\Services\ServicioEjemplo();
    }
}
