<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LezmOzT.App\Controller\UsuarioController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LezmOzT.App\\Controller\\UsuarioController::delete()'] = ($container->privates['.service_locator.LezmOzT'] ?? $container->load('get_ServiceLocator_LezmOzTService'))->withContext('App\\Controller\\UsuarioController::delete()', $container);
    }
}
