<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qpPGanN.App\Controller\UsuarioController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qpPGanN.App\\Controller\\UsuarioController::show()'] = ($container->privates['.service_locator.qpPGanN'] ?? $container->load('get_ServiceLocator_QpPGanNService'))->withContext('App\\Controller\\UsuarioController::show()', $container);
    }
}
