<?php

namespace ContainerYrvfwvt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hQMTqFb.App\Controller\UsuarioController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hQMTqFb.App\\Controller\\UsuarioController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'manager' => '?',
            'repository' => 'App\\Repository\\UsuarioRepository',
        ]))->withContext('App\\Controller\\UsuarioController::new()', $container);
    }
}
