<?php

namespace ContainerXx5j3MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLectorCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\LectorCsv' shared autowired service.
     *
     * @return \App\Services\LectorCsv
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/LectorCsv.php';

        return $container->privates['App\\Services\\LectorCsv'] = new \App\Services\LectorCsv();
    }
}
