<?php

namespace ContainerXx5j3MF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeerCsvControllerreadCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BLaFIZo.App\Controller\LeerCsvController::readCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BLaFIZo.App\\Controller\\LeerCsvController::readCsv()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csvReader' => ['privates', 'App\\Services\\LectorCsv', 'getLectorCsvService', true],
            'ejemplo' => ['privates', 'App\\Services\\ServicioEjemplo', 'getServicioEjemploService', true],
        ], [
            'csvReader' => 'App\\Services\\LectorCsv',
            'ejemplo' => 'App\\Services\\ServicioEjemplo',
        ]))->withContext('App\\Controller\\LeerCsvController::readCsv()', $container);
    }
}
